version: "3.9"

services:
  glue_jupyter_lab:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue_jupyter_lab
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
    environment:
      - AWS_PROFILE=default
      - DISABLE_SSL=true
    volumes:
      - C:\Users\sonuf\.aws:/home/glue_user/.aws
      - C:\Users\sonuf\.kaggle:/home/glue_user/.kaggle
      - ./scripts/:/home/glue_user/workspace/jupyter_workspace/
    command: ["/home/glue_user/jupyter/jupyter_start.sh"]
    stdin_open: true
    tty: true
    restart: "no"
